### ISSUE TITLE
Mongodb 2

### ISSUE THREAD

**Issue by hamzakc** [braintree/curator#52]
Thanks for a great gem.  I am really enjoying to start to use it.

One question I have is if you have any plans to support the mongo 2 ruby driver?  Some of the Api syntax has changed.  

If you have no plans I can try and take a look at implementing the upgrade.

Kind Regards
Hamza

**Comment by pgr0ss** [comment]
We don't have any plans to add support. Feel free to take a stab and submit a pull request.

**Comment by hamzakc** [comment]
Decided not to pursue mongodb after all.  I am going to use Riak instead.  So I am closing this ticket. 

Thanks.
